require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.4

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 128
