---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7.0
gemfile:
  - gemfiles/activemodel_5.0.gemfile
  - gemfiles/activemodel_5.1.gemfile
  - gemfiles/activemodel_5.2.gemfile
  - gemfiles/activemodel_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/activemodel_6.0.gemfile
